# Generated by Django 5.0.6 on 2024-06-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='femail',
            new_name='email',
        ),
    ]
